---

language: rust

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

cache: cargo

addons:
    apt:
        packages:
            - libdbus-1-dev
